FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/ballb-625a0/firestore/indexes?create_composite=Ck9wcm9qZWN0cy9iYWxsYi02MjVhMC9kYXRhYmFzZXMvKGRlZmF1bHQpL2NvbGxlY3Rpb25Hcm91cHMvcXVpelJlc3VsdHMvaW5kZXhlcy9fEAEaCgoGdXNlcklkEAEaDwoLY29tcGxldGVkQXQQAhoMCghfX25hbWVfXxAC